config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :cats, except: :destroy
  resources :cat_rental_requests, only: [:new, :create] do
    member do
      post :approve
      post :deny
    end
  end

  resources :users
  resource :session, only: [:new, :create, :destroy]

  root to: redirect('/cats')
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :bigint(8)        not null, primary key
#  user_name       :string           not null
#  password_digest :string           not null
#  session_token   :string           not null
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class User < ApplicationRecord
  validates :user_name, presence: true
  validates :password_digest, presence: { message: 'Password can\'t be blank' }
  validates :session_token, presence: true, uniqueness: true
  validates :password, length: { minimum: 6, allow_nil: true }
  attr_reader :password
  before_validation :ensure_session_token

  has_many :cats,
  foreign_key: :user_id,
  class_name: :Cat

  def ensure_session_token
    self.session_token ||= SecureRandom.urlsafe_base64
  end

  def reset_session_token!
    self.session_token = SecureRandom.urlsafe_base64
    self.save!
    self.session_token
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  def self.find_by_credentials(user_name, password)
    user = User.find_by(user_name: user_name)
    return user if user && user.is_password?(password)
    nil
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    render :new
  end

  def create
    user = User.new(user_params)
    if user.save
      login!(user)
      redirect_to cats_url
    else
      flash.now[:errors] = user.errors.full_messages
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:user_name, :password)
  end
end

app/views/users/_form.html.erb
<% if action == :sign_up %>
  <% submit_text = 'Sign Up' %>
  <% action_url = users_url %>
<% else %>
    <% submit_text = 'Login' %>
    <% action_url = session_url %>
<% end %>


<form class="" action="<%=action_url%>" method="post">

  <input
    type="hidden"
    name="authenticity_token"
    value="<%= form_authenticity_token %>">

  <label for="user_name">Username:</label>
  <input
    type="text"
    name="user[user_name]"
    id="user_name"
    value="">
  <br>
  <br>
  <label for="password">Password:</label>
  <input
    type="password"
    name="user[password]"
    id="password"
    value="">
  <br>
  <br>
  <% if flash.now[:errors] %>
    <% flash.now[:errors].each do |error| %>
      <%= error %>
    <% end %>
  <% end %>
  <input type="submit" value="<%= submit_text %>">
</form>


  <% if action == :login %>
  <form class="" action="<%=new_user_url%>" method="get">
    <br>
    Wanna sign up?
    <br>
    <input type="submit" name="" value="Join our cat factory!">
  </form>
  <% else %>
  <form class="" action="<%=new_session_url%>" method="get">
    <br>
    Already a user?
    <br>
    <input type="submit" name="" value="Log in here ;)">
  </form>
  <% end %>

app/views/users/new.html.erb
<h1>SIGN UP!!!! </h1> <h3>...please</h3>
<br>
<%= render 'form', user: @user, action: :sign_up %>